---
# Per environment values which override defaults in hmpps-arns-risk-actuarial-api/values.yaml

generic-service:
  ingress:
    host: arns-risk-actuarial-api.hmpps.service.justice.gov.uk

  env:
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    MANAGE_OFFENCES_API_URL: ""

# CloudPlatform AlertManager receiver to route prometheus alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts
generic-prometheus-alerts:
  alertSeverity: hmpps-arns-risk-actuarial-prod
